-- Pulso · módulo Horario
-- Ejecutar una vez en Supabase > SQL Editor.
-- Usa profiles(email, full_name, cargo, pdv) como fuente de asesores y PDV.

create table if not exists public.horario_turnos (
  id bigint generated by default as identity primary key,
  advisor_email text not null,
  pdv text not null,
  shift_date date not null,
  start_time time,
  end_time time,
  break_start time,
  break_end time,
  is_day_off boolean not null default false,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint horario_turnos_advisor_day_key unique (advisor_email, shift_date),
  constraint horario_turnos_valid_shift check (
    (is_day_off = true and start_time is null and end_time is null)
    or
    (is_day_off = false and start_time is not null and end_time is not null and end_time > start_time)
  ),
  constraint horario_turnos_valid_break check (
    (break_start is null and break_end is null)
    or
    (break_start is not null and break_end is not null and break_end > break_start)
  )
);

create index if not exists horario_turnos_date_pdv_idx on public.horario_turnos (shift_date, pdv);
create index if not exists horario_turnos_advisor_date_idx on public.horario_turnos (advisor_email, shift_date);

-- Estas funciones consultan el cargo de la persona autenticada dentro de la
-- base de datos. Así los permisos no dependen de lo que muestre el navegador.
create or replace function public.horario_cargo_actual()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select lower(trim(coalesce(cargo, '')))
  from public.profiles
  where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1;
$$;

create or replace function public.is_horario_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.horario_cargo_actual() in ('supervisor', 'operaciones'), false);
$$;

-- Lista restringida: los asesores no necesitan descargar los datos de otros
-- asesores. Supervisor, Operaciones y Gerente sí la usan para la cobertura.
create or replace function public.horario_roster()
returns table(email text, full_name text, pdv text)
language sql
stable
security definer
set search_path = public
as $$
  select p.email, p.full_name, p.pdv
  from public.profiles p
  where lower(trim(coalesce(p.cargo, ''))) = 'asesor'
    and public.horario_cargo_actual() <> 'asesor'
  order by p.pdv nulls last, p.full_name nulls last;
$$;

revoke all on function public.horario_cargo_actual() from public;
revoke all on function public.is_horario_editor() from public;
revoke all on function public.horario_roster() from public;
grant execute on function public.horario_cargo_actual() to authenticated;
grant execute on function public.is_horario_editor() to authenticated;
grant execute on function public.horario_roster() to authenticated;

alter table public.horario_turnos enable row level security;

drop policy if exists "horario_read_by_role" on public.horario_turnos;
drop policy if exists "horario_manage_supervisor_operaciones" on public.horario_turnos;

-- Asesor: solo sus turnos. Supervisor, Operaciones y Gerente: todos los
-- turnos para administrar o consultar la cobertura.
create policy "horario_read_by_role"
on public.horario_turnos for select to authenticated
using (
  public.horario_cargo_actual() <> 'asesor'
  or lower(advisor_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

-- Solo Supervisor y Operaciones pueden crear, modificar o eliminar turnos.
create policy "horario_manage_supervisor_operaciones"
on public.horario_turnos for all to authenticated
using (public.is_horario_editor())
with check (public.is_horario_editor());

