-- Pulso · Gestión Xstore
-- Ejecutar una vez en Supabase > SQL Editor.
-- Requiere que la estructura de Horario (003_horarios.sql) ya exista.
-- Las fotos se almacenan en el bucket privado xstore-evidencias.

create extension if not exists pgcrypto;

create table if not exists public.xstore_cash_closures (
  id uuid primary key default gen_random_uuid(),
  pdv text not null,
  cash_date date not null,
  cash_amount numeric(12,2) not null default 0 check (cash_amount >= 0),
  no_cash boolean not null default false,
  no_cash_reason text,
  evidence_path text,
  status text not null default 'pending_deposit' check (status in (
    'pending_deposit', 'deposit_review', 'validated', 'payjoy_validated',
    'difference', 'observed', 'no_cash'
  )),
  payjoy_amount numeric(12,2) not null default 0 check (payjoy_amount >= 0),
  registered_by_email text not null,
  updated_by_email text not null,
  review_started_at timestamptz,
  review_started_by_email text,
  validated_at timestamptz,
  validated_by_email text,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint xstore_cash_closures_pdv_date_key unique (pdv, cash_date),
  constraint xstore_cash_closures_no_cash_check check (
    (no_cash = false) or (cash_amount = 0)
  ),
  constraint xstore_cash_closures_payjoy_check check (payjoy_amount <= cash_amount)
);

create table if not exists public.xstore_deposits (
  id uuid primary key default gen_random_uuid(),
  pdv text not null,
  deposit_date date not null,
  deposit_amount numeric(12,2) not null check (deposit_amount > 0),
  evidence_path text not null,
  registered_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.xstore_deposit_allocations (
  id uuid primary key default gen_random_uuid(),
  deposit_id uuid not null references public.xstore_deposits(id) on delete cascade,
  closure_id uuid not null references public.xstore_cash_closures(id) on delete cascade,
  allocated_amount numeric(12,2) not null check (allocated_amount > 0),
  created_at timestamptz not null default now(),
  constraint xstore_deposit_allocations_unique unique (deposit_id, closure_id)
);

create table if not exists public.xstore_audit_log (
  id bigint generated by default as identity primary key,
  closure_id uuid references public.xstore_cash_closures(id) on delete cascade,
  action text not null,
  actor_email text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists xstore_cash_closures_pdv_date_idx on public.xstore_cash_closures (pdv, cash_date desc);
create index if not exists xstore_deposits_pdv_date_idx on public.xstore_deposits (pdv, deposit_date desc);
create index if not exists xstore_deposit_allocations_closure_idx on public.xstore_deposit_allocations (closure_id);

-- Funciones privadas de autorización. El navegador nunca decide permisos.
create or replace function public.xstore_current_email()
returns text language sql stable security definer set search_path = public as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.xstore_current_cargo()
returns text language sql stable security definer set search_path = public as $$
  select lower(trim(coalesce(cargo, '')))
  from public.profiles
  where lower(email) = public.xstore_current_email()
  limit 1;
$$;

create or replace function public.xstore_current_pdv()
returns text language sql stable security definer set search_path = public as $$
  select pdv
  from public.profiles
  where lower(email) = public.xstore_current_email()
  limit 1;
$$;

create or replace function public.xstore_is_operations()
returns boolean language sql stable security definer set search_path = public as $$
  select public.xstore_current_cargo() = 'operaciones';
$$;

create or replace function public.xstore_can_access_pdv(p_pdv text)
returns boolean language sql stable security definer set search_path = public as $$
  select case
    when public.xstore_current_cargo() = 'asesor'
      then lower(trim(coalesce(public.xstore_current_pdv(), ''))) = lower(trim(coalesce(p_pdv, '')))
    else public.xstore_current_cargo() in ('operaciones', 'supervisor', 'gerente')
  end;
$$;

create or replace function public.xstore_can_upload_path(p_name text)
returns boolean language sql stable security definer set search_path = public as $$
  select public.xstore_can_access_pdv(replace(split_part(p_name, '/', 2), '_', ' '));
$$;

revoke all on function public.xstore_current_email() from public;
revoke all on function public.xstore_current_cargo() from public;
revoke all on function public.xstore_current_pdv() from public;
revoke all on function public.xstore_is_operations() from public;
revoke all on function public.xstore_can_access_pdv(text) from public;
revoke all on function public.xstore_can_upload_path(text) from public;
grant execute on function public.xstore_current_email() to authenticated;
grant execute on function public.xstore_current_cargo() to authenticated;
grant execute on function public.xstore_current_pdv() to authenticated;
grant execute on function public.xstore_is_operations() to authenticated;
grant execute on function public.xstore_can_access_pdv(text) to authenticated;
grant execute on function public.xstore_can_upload_path(text) to authenticated;

alter table public.xstore_cash_closures enable row level security;
alter table public.xstore_deposits enable row level security;
alter table public.xstore_deposit_allocations enable row level security;
alter table public.xstore_audit_log enable row level security;

drop policy if exists "xstore_closures_read" on public.xstore_cash_closures;
create policy "xstore_closures_read" on public.xstore_cash_closures for select to authenticated
using (public.xstore_can_access_pdv(pdv));
drop policy if exists "xstore_deposits_read" on public.xstore_deposits;
create policy "xstore_deposits_read" on public.xstore_deposits for select to authenticated
using (public.xstore_can_access_pdv(pdv));
drop policy if exists "xstore_allocations_read" on public.xstore_deposit_allocations;
create policy "xstore_allocations_read" on public.xstore_deposit_allocations for select to authenticated
using (exists (select 1 from public.xstore_cash_closures c where c.id = closure_id and public.xstore_can_access_pdv(c.pdv)));
drop policy if exists "xstore_audit_read" on public.xstore_audit_log;
create policy "xstore_audit_read" on public.xstore_audit_log for select to authenticated
using (exists (select 1 from public.xstore_cash_closures c where c.id = closure_id and public.xstore_can_access_pdv(c.pdv)));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('xstore-evidencias', 'xstore-evidencias', false, 1500000, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = 1500000,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "xstore_evidence_read" on storage.objects;
create policy "xstore_evidence_read" on storage.objects for select to authenticated
using (bucket_id = 'xstore-evidencias' and public.xstore_can_upload_path(name));
drop policy if exists "xstore_evidence_insert" on storage.objects;
create policy "xstore_evidence_insert" on storage.objects for insert to authenticated
with check (bucket_id = 'xstore-evidencias' and public.xstore_can_upload_path(name));
drop policy if exists "xstore_evidence_update" on storage.objects;
create policy "xstore_evidence_update" on storage.objects for update to authenticated
using (bucket_id = 'xstore-evidencias' and public.xstore_can_upload_path(name))
with check (bucket_id = 'xstore-evidencias' and public.xstore_can_upload_path(name));

create or replace function public.xstore_add_audit(p_closure_id uuid, p_action text, p_detail jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.xstore_audit_log(closure_id, action, actor_email, detail)
  values (p_closure_id, p_action, public.xstore_current_email(), coalesce(p_detail, '{}'::jsonb));
end;
$$;

create or replace function public.xstore_submit_cash(
  p_cash_date date,
  p_cash_amount numeric,
  p_evidence_path text,
  p_no_cash boolean default false,
  p_no_cash_reason text default null
) returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_pdv text := public.xstore_current_pdv();
  v_email text := public.xstore_current_email();
  v_existing public.xstore_cash_closures;
  v_id uuid;
begin
  if public.xstore_current_cargo() <> 'asesor' or coalesce(trim(v_pdv), '') = '' then
    raise exception 'Solo un asesor con PDV asignado puede registrar caja.';
  end if;
  if p_cash_date is null or p_cash_date > current_date then raise exception 'La fecha de caja no es válida.'; end if;
  if coalesce(p_cash_amount, -1) < 0 then raise exception 'El monto de caja no es válido.'; end if;
  if coalesce(p_no_cash, false) = false and coalesce(trim(p_evidence_path), '') = '' then raise exception 'Debes adjuntar la foto de caja.'; end if;
  if coalesce(p_no_cash, false) = true and coalesce(p_cash_amount, 0) <> 0 then raise exception 'Un día sin recaudo debe tener monto cero.'; end if;

  select * into v_existing from public.xstore_cash_closures
  where pdv = v_pdv and cash_date = p_cash_date for update;
  if found then
    if v_existing.review_started_at is not null or v_existing.status in ('validated','payjoy_validated','difference') then
      raise exception 'Operaciones ya inició la revisión de este día.';
    end if;
    update public.xstore_cash_closures set
      cash_amount = coalesce(p_cash_amount, 0), no_cash = coalesce(p_no_cash, false),
      no_cash_reason = case when coalesce(p_no_cash, false) then nullif(trim(p_no_cash_reason), '') else null end,
      evidence_path = nullif(trim(p_evidence_path), ''),
      status = case when coalesce(p_no_cash, false) then 'no_cash' else 'pending_deposit' end,
      updated_by_email = v_email, updated_at = now(), payjoy_amount = 0,
      review_note = null, validated_at = null, validated_by_email = null
    where id = v_existing.id returning id into v_id;
    perform public.xstore_add_audit(v_id, 'caja_actualizada', jsonb_build_object('monto', p_cash_amount));
  else
    insert into public.xstore_cash_closures(
      pdv, cash_date, cash_amount, no_cash, no_cash_reason, evidence_path,
      status, registered_by_email, updated_by_email
    ) values (
      v_pdv, p_cash_date, coalesce(p_cash_amount, 0), coalesce(p_no_cash, false),
      case when coalesce(p_no_cash, false) then nullif(trim(p_no_cash_reason), '') else null end,
      nullif(trim(p_evidence_path), ''), case when coalesce(p_no_cash, false) then 'no_cash' else 'pending_deposit' end,
      v_email, v_email
    ) returning id into v_id;
    perform public.xstore_add_audit(v_id, 'caja_registrada', jsonb_build_object('monto', p_cash_amount));
  end if;
  return v_id;
end;
$$;

create or replace function public.xstore_submit_deposit(
  p_deposit_date date,
  p_deposit_amount numeric,
  p_evidence_path text,
  p_allocations jsonb
) returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_pdv text := public.xstore_current_pdv();
  v_email text := public.xstore_current_email();
  v_deposit_id uuid;
  v_total numeric;
  v_invalid integer;
begin
  if public.xstore_current_cargo() <> 'asesor' or coalesce(trim(v_pdv), '') = '' then
    raise exception 'Solo un asesor con PDV asignado puede registrar depósitos.';
  end if;
  if p_deposit_date is null or p_deposit_date > current_date then raise exception 'La fecha de depósito no es válida.'; end if;
  if coalesce(p_deposit_amount, 0) <= 0 or coalesce(trim(p_evidence_path), '') = '' then raise exception 'Monto y voucher son obligatorios.'; end if;
  select coalesce(sum((item->>'amount')::numeric), 0) into v_total from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb)) item;
  if abs(v_total - p_deposit_amount) > 0.01 then raise exception 'La suma asignada debe coincidir con el depósito.'; end if;
  if jsonb_array_length(coalesce(p_allocations, '[]'::jsonb)) = 0 then raise exception 'Selecciona al menos un día de caja.'; end if;

  select count(*) into v_invalid
  from jsonb_to_recordset(p_allocations) as a(closure_id uuid, amount numeric)
  left join public.xstore_cash_closures c on c.id = a.closure_id
  where c.id is null or c.pdv <> v_pdv or c.no_cash or c.review_started_at is not null
    or c.status in ('validated','payjoy_validated','difference') or a.amount <= 0;
  if v_invalid > 0 then raise exception 'Uno de los días seleccionados ya no admite depósitos.'; end if;

  insert into public.xstore_deposits(pdv, deposit_date, deposit_amount, evidence_path, registered_by_email)
  values(v_pdv, p_deposit_date, p_deposit_amount, p_evidence_path, v_email) returning id into v_deposit_id;
  insert into public.xstore_deposit_allocations(deposit_id, closure_id, allocated_amount)
  select v_deposit_id, a.closure_id, a.amount
  from jsonb_to_recordset(p_allocations) as a(closure_id uuid, amount numeric);
  update public.xstore_cash_closures c set status = 'deposit_review', updated_at = now(), updated_by_email = v_email
  where c.id in (select (item->>'closure_id')::uuid from jsonb_array_elements(p_allocations) item);
  perform public.xstore_add_audit((select (item->>'closure_id')::uuid from jsonb_array_elements(p_allocations) item limit 1), 'deposito_registrado', jsonb_build_object('deposito_id', v_deposit_id, 'monto', p_deposit_amount));
  return v_deposit_id;
end;
$$;

create or replace function public.xstore_start_review(p_closure_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede iniciar una revisión.'; end if;
  update public.xstore_cash_closures set review_started_at = now(), review_started_by_email = public.xstore_current_email(), updated_at = now()
  where id = p_closure_id and review_started_at is null;
  if not found then raise exception 'El caso no existe o ya está en revisión.'; end if;
  perform public.xstore_add_audit(p_closure_id, 'revision_iniciada');
end;
$$;

create or replace function public.xstore_resolve_closure(
  p_closure_id uuid, p_resolution text, p_payjoy_amount numeric default 0, p_note text default null
) returns void language plpgsql security definer set search_path = public as $$
declare
  v_cash numeric; v_deposited numeric; v_expected numeric; v_status text;
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede validar o corregir.'; end if;
  select cash_amount into v_cash from public.xstore_cash_closures where id = p_closure_id for update;
  if not found then raise exception 'No se encontró el cierre.'; end if;
  select coalesce(sum(allocated_amount),0) into v_deposited from public.xstore_deposit_allocations where closure_id = p_closure_id;
  if p_resolution = 'validated' then v_status := 'validated'; p_payjoy_amount := 0;
  elsif p_resolution = 'payjoy_validated' then v_status := 'payjoy_validated';
  elsif p_resolution = 'difference' then v_status := 'difference';
  elsif p_resolution = 'observed' then
    update public.xstore_cash_closures set status='observed', review_started_at=null, review_started_by_email=null,
      review_note=nullif(trim(p_note),''), updated_at=now(), updated_by_email=public.xstore_current_email()
    where id=p_closure_id;
    perform public.xstore_add_audit(p_closure_id, 'observado', jsonb_build_object('nota',p_note)); return;
  else raise exception 'Resolución no válida.'; end if;
  v_expected := v_cash - coalesce(p_payjoy_amount,0);
  if v_status in ('validated','payjoy_validated') and abs(v_deposited - v_expected) > 0.01 then
    raise exception 'El depósito asignado no cuadra con el monto esperado.';
  end if;
  update public.xstore_cash_closures set status=v_status, payjoy_amount=coalesce(p_payjoy_amount,0), review_note=nullif(trim(p_note),''),
    validated_at=now(), validated_by_email=public.xstore_current_email(), updated_at=now(), updated_by_email=public.xstore_current_email()
  where id=p_closure_id;
  perform public.xstore_add_audit(p_closure_id, v_status, jsonb_build_object('payjoy',p_payjoy_amount,'nota',p_note));
end;
$$;

create or replace function public.xstore_dashboard_rows(p_from date, p_to date)
returns table(
  closure_id uuid, pdv text, cash_date date, status text, cash_amount numeric,
  payjoy_amount numeric, deposit_amount numeric, expected_amount numeric, outstanding_amount numeric,
  registered_by_email text, updated_by_email text, review_started_at timestamptz,
  review_started_by_email text, validated_by_email text, review_note text, no_cash boolean, evidence_path text
) language sql stable security definer set search_path = public as $$
  with scheduled as (
    select distinct h.pdv, h.shift_date as cash_date
    from public.horario_turnos h
    where h.shift_date between p_from and p_to and h.is_day_off = false
  ), expected as (
    select pdv, cash_date from scheduled
    union
    select pdv, cash_date from public.xstore_cash_closures where cash_date between p_from and p_to
  ), deposits as (
    select a.closure_id, coalesce(sum(a.allocated_amount),0) as total
    from public.xstore_deposit_allocations a group by a.closure_id
  )
  select c.id, e.pdv, e.cash_date,
    case when c.id is null then 'missing_cash' else c.status end,
    c.cash_amount, coalesce(c.payjoy_amount,0), coalesce(d.total,0),
    case when c.id is null then null else c.cash_amount - coalesce(c.payjoy_amount,0) end,
    case when c.id is null then null else greatest((c.cash_amount - coalesce(c.payjoy_amount,0)) - coalesce(d.total,0),0) end,
    c.registered_by_email, c.updated_by_email, c.review_started_at, c.review_started_by_email,
    c.validated_by_email, c.review_note, coalesce(c.no_cash,false), c.evidence_path
  from expected e
  left join public.xstore_cash_closures c on c.pdv=e.pdv and c.cash_date=e.cash_date
  left join deposits d on d.closure_id=c.id
  where public.xstore_can_access_pdv(e.pdv)
  order by e.cash_date desc, e.pdv;
$$;

create or replace function public.xstore_monthly_deposits(p_from date, p_to date)
returns table(deposit_id uuid, pdv text, deposit_date date, deposit_amount numeric, registered_by_email text, evidence_path text, allocations jsonb)
language sql stable security definer set search_path = public as $$
  select d.id, d.pdv, d.deposit_date, d.deposit_amount, d.registered_by_email, d.evidence_path,
    coalesce(jsonb_agg(jsonb_build_object('closure_id', c.id, 'fecha_caja', c.cash_date, 'monto', a.allocated_amount) order by c.cash_date) filter (where a.id is not null), '[]'::jsonb)
  from public.xstore_deposits d
  left join public.xstore_deposit_allocations a on a.deposit_id=d.id
  left join public.xstore_cash_closures c on c.id=a.closure_id
  where d.deposit_date between p_from and p_to and public.xstore_can_access_pdv(d.pdv)
  group by d.id
  order by d.deposit_date desc, d.pdv;
$$;

-- El frontend usa únicamente RPC: las tablas no se exponen directamente.
revoke all on table public.xstore_cash_closures from anon, authenticated;
revoke all on table public.xstore_deposits from anon, authenticated;
revoke all on table public.xstore_deposit_allocations from anon, authenticated;
revoke all on table public.xstore_audit_log from anon, authenticated;

-- Las funciones SECURITY DEFINER no deben quedar ejecutables para anon/public.
revoke all on function public.xstore_add_audit(uuid, text, jsonb) from public;
revoke all on function public.xstore_submit_cash(date, numeric, text, boolean, text) from public;
revoke all on function public.xstore_submit_deposit(date, numeric, text, jsonb) from public;
revoke all on function public.xstore_start_review(uuid) from public;
revoke all on function public.xstore_resolve_closure(uuid, text, numeric, text) from public;
revoke all on function public.xstore_dashboard_rows(date, date) from public;
revoke all on function public.xstore_monthly_deposits(date, date) from public;
revoke execute on function public.xstore_current_email() from anon;
revoke execute on function public.xstore_current_cargo() from anon;
revoke execute on function public.xstore_current_pdv() from anon;
revoke execute on function public.xstore_is_operations() from anon;
revoke execute on function public.xstore_can_access_pdv(text) from anon;
revoke execute on function public.xstore_can_upload_path(text) from anon;
revoke execute on function public.xstore_add_audit(uuid, text, jsonb) from anon, authenticated;
revoke execute on function public.xstore_submit_cash(date, numeric, text, boolean, text) from anon;
revoke execute on function public.xstore_submit_deposit(date, numeric, text, jsonb) from anon;
revoke execute on function public.xstore_start_review(uuid) from anon;
revoke execute on function public.xstore_resolve_closure(uuid, text, numeric, text) from anon;
revoke execute on function public.xstore_dashboard_rows(date, date) from anon;
revoke execute on function public.xstore_monthly_deposits(date, date) from anon;
grant execute on function public.xstore_submit_cash(date, numeric, text, boolean, text) to authenticated;
grant execute on function public.xstore_submit_deposit(date, numeric, text, jsonb) to authenticated;
grant execute on function public.xstore_start_review(uuid) to authenticated;
grant execute on function public.xstore_resolve_closure(uuid, text, numeric, text) to authenticated;
grant execute on function public.xstore_dashboard_rows(date, date) to authenticated;
grant execute on function public.xstore_monthly_deposits(date, date) to authenticated;
