-- Gestión Xstore independiente de Horario.
-- Preparado para ejecutarse UNA VEZ en Supabase SQL Editor cuando el módulo local sea aprobado.
-- No crear ni modificar vistas existentes: trabaja solo con tablas/funciones xstore_.
-- Esta migración reemplaza las funciones de 004 a 007: después de ejecutarla, no vuelvas a correr esos archivos.

create extension if not exists pgcrypto;

create table if not exists public.xstore_cash_closures (
  id uuid primary key default gen_random_uuid(),
  pdv text not null,
  cash_date date not null,
  cash_amount numeric(12,2) not null default 0 check (cash_amount >= 0),
  store_closed boolean not null default false,
  store_closed_reason text,
  evidence_path text,
  status text not null default 'pending_deposit' check (status in ('pending_deposit','deposit_review','validated','payjoy_validated','difference','observed','store_closed')),
  payjoy_amount numeric(12,2) not null default 0 check (payjoy_amount >= 0),
  registered_by_email text not null,
  updated_by_email text not null,
  review_started_at timestamptz,
  review_started_by_email text,
  validated_at timestamptz,
  validated_by_email text,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint xstore_cash_closures_pdv_date_key unique (pdv, cash_date)
);

alter table public.xstore_cash_closures add column if not exists store_closed boolean not null default false;
alter table public.xstore_cash_closures add column if not exists store_closed_reason text;
-- Compatibilidad con pruebas del prototipo anterior: "no_cash" pasa a ser cierre de tienda.
update public.xstore_cash_closures set status='store_closed', store_closed=true
where status='no_cash';
alter table public.xstore_cash_closures drop constraint if exists xstore_cash_closures_status_check;
alter table public.xstore_cash_closures add constraint xstore_cash_closures_status_check
  check (status in ('pending_deposit','deposit_review','validated','payjoy_validated','difference','observed','store_closed'));

create table if not exists public.xstore_deposits (
  id uuid primary key default gen_random_uuid(),
  pdv text not null,
  deposit_date date not null,
  deposit_amount numeric(12,2) not null check (deposit_amount > 0),
  evidence_path text not null,
  registered_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.xstore_deposit_allocations (
  id uuid primary key default gen_random_uuid(),
  deposit_id uuid not null references public.xstore_deposits(id) on delete cascade,
  closure_id uuid not null references public.xstore_cash_closures(id) on delete cascade,
  allocated_amount numeric(12,2) not null check (allocated_amount > 0),
  created_at timestamptz not null default now(),
  constraint xstore_deposit_allocations_unique unique (deposit_id, closure_id)
);

create table if not exists public.xstore_audit_log (
  id bigint generated by default as identity primary key,
  closure_id uuid references public.xstore_cash_closures(id) on delete cascade,
  action text not null,
  actor_email text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists xstore_cash_closures_pdv_date_idx on public.xstore_cash_closures(pdv, cash_date desc);
create index if not exists xstore_deposits_pdv_date_idx on public.xstore_deposits(pdv, deposit_date desc);
create index if not exists xstore_allocations_closure_idx on public.xstore_deposit_allocations(closure_id);

-- Autorización: siempre se evalúa en la base; el navegador nunca decide permisos.
create or replace function public.xstore_current_email()
returns text language sql stable security definer set search_path = public as $$
  select lower(coalesce(auth.jwt()->>'email',''));
$$;

create or replace function public.xstore_current_cargo()
returns text language sql stable security definer set search_path = public as $$
  select lower(trim(coalesce(cargo,''))) from public.profiles
  where lower(email) = public.xstore_current_email() limit 1;
$$;

create or replace function public.xstore_current_pdv()
returns text language sql stable security definer set search_path = public as $$
  select pdv from public.profiles where lower(email) = public.xstore_current_email() limit 1;
$$;

create or replace function public.xstore_pdv_key(p_value text)
returns text language sql immutable as $$
  select trim(both '_' from regexp_replace(lower(translate(coalesce(p_value,''),'ÁÉÍÓÚÜÑáéíóúüñ','AEIOUUNaeiouun')),'[^a-z0-9]+','_','g'));
$$;

-- Re-declare after legacy normalization to make this migration robust when read
-- under Windows code pages; Unicode escapes preserve accented PDV names.
create or replace function public.xstore_pdv_key(p_value text)
returns text language sql immutable as $$
  select trim(both '_' from regexp_replace(
    replace(replace(replace(replace(replace(replace(replace(
      lower(coalesce(p_value,'')),
      U&'\00E1','a'), U&'\00E9','e'), U&'\00ED','i'), U&'\00F3','o'),
      U&'\00FA','u'), U&'\00FC','u'), U&'\00F1','n'),
    '[^a-z0-9]+','_','g'
  ));
$$;

create or replace function public.xstore_can_access_pdv(p_pdv text)
returns boolean language sql stable security definer set search_path = public as $$
  -- Un usuario autenticado sin perfil no obtiene acceso por defecto.
  -- Asesor: solamente su propio PDV. Los cargos de gestiÃ³n ven PDV existentes.
  select case
    when not exists (select 1 from public.profiles p where lower(p.email) = public.xstore_current_email()) then false
    when public.xstore_current_cargo() = 'asesor'
      then lower(trim(coalesce(public.xstore_current_pdv(),''))) = lower(trim(coalesce(p_pdv,'')))
    when public.xstore_current_cargo() in ('supervisor','operaciones','gerente','gerencia')
      then exists(select 1 from public.profiles p where lower(trim(coalesce(p.pdv,''))) = lower(trim(coalesce(p_pdv,''))))
    else false
  end;
$$;

create or replace function public.xstore_is_operations()
returns boolean language sql stable security definer set search_path = public as $$
  select public.xstore_current_cargo() = 'operaciones';
$$;

create or replace function public.xstore_can_upload_path(p_name text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from public.profiles p
    where public.xstore_pdv_key(p.pdv) = split_part(p_name,'/',2)
      and public.xstore_can_access_pdv(p.pdv)
  );
$$;

create or replace function public.xstore_add_audit(p_closure_id uuid, p_action text, p_detail jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.xstore_audit_log(closure_id,action,actor_email,detail)
  values(p_closure_id,p_action,public.xstore_current_email(),coalesce(p_detail,'{}'::jsonb));
end;
$$;

-- Se reemplazan las firmas antiguas para que no exista ambigüedad en PostgREST.
drop function if exists public.xstore_submit_cash(date,numeric,text,boolean,text);
drop function if exists public.xstore_submit_deposit(date,numeric,text,jsonb);
drop function if exists public.xstore_dashboard_rows(date,date);
drop function if exists public.xstore_monthly_deposits(date,date);

create or replace function public.xstore_submit_cash(
  p_pdv text, p_cash_date date, p_cash_amount numeric, p_evidence_path text,
  p_store_closed boolean default false, p_store_closed_reason text default null
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_current public.xstore_cash_closures; v_email text := public.xstore_current_email();
begin
  if not public.xstore_can_access_pdv(p_pdv) then raise exception 'No tienes permiso para registrar en este PDV.'; end if;
  if p_cash_date is null or p_cash_date > current_date then raise exception 'La fecha de caja no es válida.'; end if;
  if coalesce(p_cash_amount,-1) < 0 then raise exception 'El monto no es válido.'; end if;
  if coalesce(p_store_closed,false) then
    if coalesce(p_cash_amount,0) <> 0 then raise exception 'Una tienda que no abrió debe registrar S/ 0.00.'; end if;
  elsif nullif(trim(coalesce(p_evidence_path,'')),'') is null then
    raise exception 'Debes adjuntar la foto de caja.';
  end if;
  select * into v_current from public.xstore_cash_closures where pdv=p_pdv and cash_date=p_cash_date for update;
  if found and (v_current.review_started_at is not null or v_current.status in ('validated','payjoy_validated','difference','store_closed')) then
    raise exception 'Este registro ya está cerrado o en revisión por Operaciones.';
  end if;
  if found then
    update public.xstore_cash_closures set
      cash_amount=coalesce(p_cash_amount,0), store_closed=coalesce(p_store_closed,false),
      store_closed_reason=case when coalesce(p_store_closed,false) then nullif(trim(p_store_closed_reason),'') else null end,
      evidence_path=case when coalesce(p_store_closed,false) then null else nullif(trim(p_evidence_path),'') end,
      status=case when coalesce(p_store_closed,false) then 'store_closed' else 'pending_deposit' end,
      payjoy_amount=0, review_note=null, validated_at=case when coalesce(p_store_closed,false) then now() else null end,
      validated_by_email=case when coalesce(p_store_closed,false) then v_email else null end,
      updated_at=now(), updated_by_email=v_email, review_started_at=null, review_started_by_email=null
    where id=v_current.id returning id into v_id;
    perform public.xstore_add_audit(v_id,'caja_actualizada',jsonb_build_object('monto',p_cash_amount,'tienda_no_abrio',p_store_closed));
  else
    insert into public.xstore_cash_closures(pdv,cash_date,cash_amount,store_closed,store_closed_reason,evidence_path,status,registered_by_email,updated_by_email,validated_at,validated_by_email)
    values(p_pdv,p_cash_date,coalesce(p_cash_amount,0),coalesce(p_store_closed,false),case when coalesce(p_store_closed,false) then nullif(trim(p_store_closed_reason),'') else null end,case when coalesce(p_store_closed,false) then null else nullif(trim(p_evidence_path),'') end,case when coalesce(p_store_closed,false) then 'store_closed' else 'pending_deposit' end,v_email,v_email,case when coalesce(p_store_closed,false) then now() else null end,case when coalesce(p_store_closed,false) then v_email else null end)
    returning id into v_id;
    perform public.xstore_add_audit(v_id,'caja_registrada',jsonb_build_object('monto',p_cash_amount,'tienda_no_abrio',p_store_closed));
  end if;
  return v_id;
end;
$$;

create or replace function public.xstore_submit_deposit(
  p_pdv text, p_deposit_date date, p_deposit_amount numeric, p_evidence_path text, p_allocations jsonb
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_sum numeric; v_invalid integer; v_email text := public.xstore_current_email();
begin
  if not public.xstore_can_access_pdv(p_pdv) then raise exception 'No tienes permiso para registrar en este PDV.'; end if;
  if p_deposit_date is null or p_deposit_date > current_date then raise exception 'La fecha del depósito no es válida.'; end if;
  if coalesce(p_deposit_amount,0) <= 0 or nullif(trim(coalesce(p_evidence_path,'')),'') is null then raise exception 'Monto y voucher son obligatorios.'; end if;
  if jsonb_array_length(coalesce(p_allocations,'[]'::jsonb)) = 0 then raise exception 'Selecciona al menos una fecha de caja.'; end if;
  select coalesce(sum((item->>'amount')::numeric),0) into v_sum from jsonb_array_elements(p_allocations) item;
  if abs(v_sum-p_deposit_amount) > .01 then raise exception 'La suma de los días debe coincidir con el voucher.'; end if;
  select count(*) into v_invalid from jsonb_to_recordset(p_allocations) a(closure_id uuid,amount numeric)
  left join public.xstore_cash_closures c on c.id=a.closure_id
  where c.id is null or c.pdv<>p_pdv or c.store_closed or c.review_started_at is not null
    or c.status in ('validated','payjoy_validated','difference') or a.amount<=0
    or a.amount > (c.cash_amount-c.payjoy_amount-coalesce((select sum(x.allocated_amount) from public.xstore_deposit_allocations x where x.closure_id=c.id),0));
  if v_invalid > 0 then raise exception 'Una fecha seleccionada ya no admite depósito o supera su saldo.'; end if;
  insert into public.xstore_deposits(pdv,deposit_date,deposit_amount,evidence_path,registered_by_email)
  values(p_pdv,p_deposit_date,p_deposit_amount,p_evidence_path,v_email) returning id into v_id;
  insert into public.xstore_deposit_allocations(deposit_id,closure_id,allocated_amount)
  select v_id,a.closure_id,a.amount from jsonb_to_recordset(p_allocations) a(closure_id uuid,amount numeric);
  update public.xstore_cash_closures set status='deposit_review',updated_at=now(),updated_by_email=v_email
  where id in(select (item->>'closure_id')::uuid from jsonb_array_elements(p_allocations)item);
  return v_id;
end;
$$;

create or replace function public.xstore_correct_cash_amount(p_closure_id uuid,p_cash_amount numeric,p_note text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v_owner text;
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede corregir un recaudo.'; end if;
  if coalesce(p_cash_amount,-1)<0 then raise exception 'El monto no es válido.'; end if;
  select review_started_by_email into v_owner from public.xstore_cash_closures where id=p_closure_id;
  if v_owner is not null and v_owner <> public.xstore_current_email() then raise exception 'Este caso está en revisión por otro usuario de Operaciones.'; end if;
  update public.xstore_cash_closures set
    cash_amount=p_cash_amount,
    -- Cualquier corrección vuelve a evaluar el caso: conserva depósitos, pero nunca deja una validación antigua vigente.
    status=case when exists(select 1 from public.xstore_deposit_allocations a where a.closure_id=p_closure_id) then 'deposit_review' else 'pending_deposit' end,
    payjoy_amount=0,validated_at=null,validated_by_email=null,review_started_at=null,review_started_by_email=null,
    updated_at=now(),updated_by_email=public.xstore_current_email(),review_note=coalesce(nullif(trim(p_note),''),review_note)
  where id=p_closure_id and not store_closed;
  if not found then raise exception 'No se puede corregir este registro.'; end if;
  perform public.xstore_add_audit(p_closure_id,'recaudo_corregido',jsonb_build_object('monto',p_cash_amount,'nota',p_note));
end;
$$;

-- Bloquea el registro cuando Operaciones abre la conciliación.
create or replace function public.xstore_start_review(p_closure_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v_owner text;
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede conciliar.'; end if;
  select review_started_by_email into v_owner
  from public.xstore_cash_closures
  where id=p_closure_id and not store_closed and status not in ('validated','payjoy_validated','difference') for update;
  if not found then raise exception 'Este recaudo no está disponible para conciliación.'; end if;
  if v_owner is not null and v_owner <> public.xstore_current_email() then raise exception 'Este caso ya está en revisión por otro usuario de Operaciones.'; end if;
  update public.xstore_cash_closures
  set review_started_at=now(),review_started_by_email=public.xstore_current_email(),updated_at=now(),updated_by_email=public.xstore_current_email()
  where id=p_closure_id;
  perform public.xstore_add_audit(p_closure_id,'revision_iniciada','{}'::jsonb);
end;
$$;

-- Al cerrar el panel sin resolver, se libera el registro para que pueda corregirse.
create or replace function public.xstore_release_review(p_closure_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede administrar la conciliación.'; end if;
  update public.xstore_cash_closures
  set review_started_at=null,review_started_by_email=null,updated_at=now(),updated_by_email=public.xstore_current_email()
  where id=p_closure_id and review_started_by_email=public.xstore_current_email()
    and status not in ('validated','payjoy_validated','difference','store_closed');
  if not found then raise exception 'No puedes cerrar una revisión iniciada por otro usuario.'; end if;
  perform public.xstore_add_audit(p_closure_id,'revision_liberada','{}'::jsonb);
end;
$$;

create or replace function public.xstore_resolve_closure(p_closure_id uuid,p_resolution text,p_payjoy_amount numeric default 0,p_note text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v_cash numeric; v_deposited numeric; v_expected numeric; v_status text; v_owner text;
begin
  if not public.xstore_is_operations() then raise exception 'Solo Operaciones puede conciliar.'; end if;
  select cash_amount,review_started_by_email into v_cash,v_owner from public.xstore_cash_closures where id=p_closure_id and not store_closed for update;
  if not found then raise exception 'No se encontró un recaudo conciliable.'; end if;
  if v_owner is not null and v_owner <> public.xstore_current_email() then raise exception 'Este caso está en revisión por otro usuario de Operaciones.'; end if;
  select coalesce(sum(allocated_amount),0) into v_deposited from public.xstore_deposit_allocations where closure_id=p_closure_id;
  if p_resolution='validated' then v_status='validated'; p_payjoy_amount:=0;
  elsif p_resolution='payjoy_validated' then v_status='payjoy_validated';
  elsif p_resolution='difference' then v_status='difference';
  elsif p_resolution='observed' then
    update public.xstore_cash_closures set status='observed',review_started_at=null,review_started_by_email=null,review_note=nullif(trim(p_note),''),updated_at=now(),updated_by_email=public.xstore_current_email() where id=p_closure_id;
    perform public.xstore_add_audit(p_closure_id,'observado',jsonb_build_object('nota',p_note)); return;
  else raise exception 'Resolución no válida.'; end if;
  if coalesce(p_payjoy_amount,0)<0 or coalesce(p_payjoy_amount,0)>v_cash then raise exception 'Monto PayJoy no válido.'; end if;
  v_expected:=v_cash-coalesce(p_payjoy_amount,0);
  if v_status in ('validated','payjoy_validated') and abs(v_deposited-v_expected)>.01 then raise exception 'El depósito asignado no cuadra con el recaudo esperado.'; end if;
  update public.xstore_cash_closures set status=v_status,payjoy_amount=coalesce(p_payjoy_amount,0),review_note=nullif(trim(p_note),''),validated_at=now(),validated_by_email=public.xstore_current_email(),updated_at=now(),updated_by_email=public.xstore_current_email(),review_started_at=now(),review_started_by_email=public.xstore_current_email() where id=p_closure_id;
  perform public.xstore_add_audit(p_closure_id,v_status,jsonb_build_object('payjoy',p_payjoy_amount,'nota',p_note));
end;
$$;

create or replace function public.xstore_dashboard_rows(p_from date,p_to date)
returns table(closure_id uuid,pdv text,cash_date date,status text,cash_amount numeric,payjoy_amount numeric,deposit_amount numeric,expected_amount numeric,outstanding_amount numeric,registered_by_email text,updated_by_email text,review_started_at timestamptz,review_started_by_email text,validated_by_email text,review_note text,store_closed boolean,evidence_path text)
language sql stable security definer set search_path=public as $$
  with pdvs as (select distinct trim(pdv) pdv from public.profiles where nullif(trim(coalesce(pdv,'')),'') is not null),
  expected as (select p.pdv,d::date cash_date from pdvs p cross join generate_series(p_from,p_to,interval '1 day') d),
  deposited as (select closure_id,sum(allocated_amount) amount from public.xstore_deposit_allocations group by closure_id)
  select c.id,e.pdv,e.cash_date,coalesce(c.status,'missing_cash'),c.cash_amount,coalesce(c.payjoy_amount,0),coalesce(d.amount,0),
    case when c.id is null then null else c.cash_amount-coalesce(c.payjoy_amount,0) end,
    case when c.id is null then null else greatest(c.cash_amount-coalesce(c.payjoy_amount,0)-coalesce(d.amount,0),0) end,
    c.registered_by_email,c.updated_by_email,c.review_started_at,c.review_started_by_email,c.validated_by_email,c.review_note,coalesce(c.store_closed,false),c.evidence_path
  from expected e left join public.xstore_cash_closures c on c.pdv=e.pdv and c.cash_date=e.cash_date
  left join deposited d on d.closure_id=c.id where public.xstore_can_access_pdv(e.pdv)
  order by e.cash_date desc,e.pdv;
$$;

create or replace function public.xstore_monthly_deposits(p_from date,p_to date)
returns table(deposit_id uuid,pdv text,deposit_date date,deposit_amount numeric,registered_by_email text,evidence_path text,allocations jsonb)
language sql stable security definer set search_path=public as $$
  select d.id,d.pdv,d.deposit_date,d.deposit_amount,d.registered_by_email,d.evidence_path,
    coalesce(jsonb_agg(jsonb_build_object('closure_id',c.id,'fecha_caja',c.cash_date,'monto',a.allocated_amount) order by c.cash_date) filter(where a.id is not null),'[]'::jsonb)
  from public.xstore_deposits d left join public.xstore_deposit_allocations a on a.deposit_id=d.id left join public.xstore_cash_closures c on c.id=a.closure_id
  where d.deposit_date between p_from and p_to and public.xstore_can_access_pdv(d.pdv) group by d.id order by d.deposit_date desc,d.pdv;
$$;

-- Las tablas no quedan expuestas directamente; solamente las RPC anteriores.
alter table public.xstore_cash_closures enable row level security;
alter table public.xstore_deposits enable row level security;
alter table public.xstore_deposit_allocations enable row level security;
alter table public.xstore_audit_log enable row level security;
revoke all on table public.xstore_cash_closures,public.xstore_deposits,public.xstore_deposit_allocations,public.xstore_audit_log from anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('xstore-evidencias','xstore-evidencias',false,1500000,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=1500000,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
drop policy if exists "xstore_evidence_read" on storage.objects;
create policy "xstore_evidence_read" on storage.objects for select to authenticated using(bucket_id='xstore-evidencias' and public.xstore_can_upload_path(name));
drop policy if exists "xstore_evidence_insert" on storage.objects;
create policy "xstore_evidence_insert" on storage.objects for insert to authenticated with check(bucket_id='xstore-evidencias' and public.xstore_can_upload_path(name));
-- La evidencia no se reemplaza directamente: cada corrección deja una nueva carga trazable.
drop policy if exists "xstore_evidence_update" on storage.objects;
drop policy if exists "xstore_evidence_delete" on storage.objects;

revoke all on function public.xstore_submit_cash(text,date,numeric,text,boolean,text),public.xstore_submit_deposit(text,date,numeric,text,jsonb),public.xstore_correct_cash_amount(uuid,numeric,text),public.xstore_start_review(uuid),public.xstore_release_review(uuid),public.xstore_resolve_closure(uuid,text,numeric,text),public.xstore_dashboard_rows(date,date),public.xstore_monthly_deposits(date,date) from public,anon;
grant execute on function public.xstore_submit_cash(text,date,numeric,text,boolean,text),public.xstore_submit_deposit(text,date,numeric,text,jsonb),public.xstore_correct_cash_amount(uuid,numeric,text),public.xstore_start_review(uuid),public.xstore_release_review(uuid),public.xstore_resolve_closure(uuid,text,numeric,text),public.xstore_dashboard_rows(date,date),public.xstore_monthly_deposits(date,date) to authenticated;
revoke all on function public.xstore_current_email(),public.xstore_current_cargo(),public.xstore_current_pdv(),public.xstore_pdv_key(text),public.xstore_can_access_pdv(text),public.xstore_is_operations(),public.xstore_add_audit(uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.xstore_can_upload_path(text) from public;
grant execute on function public.xstore_can_upload_path(text) to authenticated;
